### ISSUE TITLE
The README file seems to have an error.

### ISSUE THREAD

**Issue by imjoe-dev** [globocom/go-buffer#8]
When copying and pasting the README file examples, an error pops up. The **WithFlusher** method now accepts an interface that the example doesn't implement.

![image](https://github.com/globocom/go-buffer/assets/67883887/34405b14-a788-460a-b2e9-3ed44239ee2e)

If this is an error in the README, I would like to create a pull request (PR) to fix it.

**Comment by mbenford** [comment]
Nice catch! Yes, please send in a PR! :)

**Comment by imjoe-dev** [comment]
Thanks, i created this [PR](https://github.com/globocom/go-buffer/pull/9) that fixes the README
